version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
      - POSTGRES_DB_FILE=/run/secrets/psql_db
    secrets:
      - psql_password
      - psql_db
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command:
      - /bin/sh
      - -c
      - |
        ngrok http web:3001
    depends_on:
      - web

  web:
    build: .
    image: syntaf/wagbag
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
      - TWILIO_ACCOUNT_SID_FILE=/run/secrets/twilio_account_sid
      - TWILIO_AUTH_TOKEN_FILE=/run/secrets/twilio_auth_token
      - TWILIO_PHONE_NUMBER_FILE=/run/secrets/twilio_phone_number
      - PORT=3001
    secrets:
      - psql_password
      - twilio_account_sid
      - twilio_auth_token
      - twilio_phone_number
    volumes:
      - .:/opt/wagbag
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  postgres_database:
    external: true

secrets:
  psql_password:
    file: ./dev-secrets/psql_password.txt
  psql_db:
    file: ./dev-secrets/psql_db.txt
  twilio_account_sid:
    file: ./dev-secrets/twilio_account_sid.txt
  twilio_auth_token:
    file: ./dev-secrets/twilio_auth_token.txt
  twilio_phone_number:
    file: ./dev-secrets/twilio_phone_number.txt