version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
      - POSTGRES_DB_FILE=/run/secrets/psql_db
    secrets:
      - psql_password
      - psql_db
    volumes:
      - .:/opt/wagbag
  web:
    build: .
    image: syntaf/wagbag
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
    secrets:
      - psql_password
    volumes:
      - .:/opt/wagbag
    ports:
      - "3000:3000"
    depends_on:
      - db

secrets:
  psql_password:
    file: ./dev-secrets/psql_password.txt
  psql_db:
    file: ./dev-secrets/psql_db.txt